service: aws-polly-poc
frameworkVersion: '>= 3 < 4'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  stackTags:
    version: 1.0.0
    service: ${self:service}-${self:custom.stage}
  region: us-east-1
  deploymentBucket: serverless-deployment-${self:provider.region}
  logRetentionInDays: 3
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    STAGE_ENV: ${self:custom.stage}
    
custom:
  webpack:
    keepOutputDirectory: true
    includeModules: true
    webpackConfig: ./webpack.config.js
    forceExclude:
      - aws-sdk
    packager: 'yarn'
    packagerOptions:
      scripts:
        - rm -rf node_modules/aws-sdk
        
package:
  individually: true

functions:
  tts: ${file(infra/functions/tts.yml)}

resources:
  - ${file(infra/resources/conditions.yml)}
  
plugins:
  - serverless-iam-roles-per-function
  - serverless-webpack